### ISSUE TITLE
As a user, I want to provide my own colors so I can completely customize the look and feel of Homechart

### ISSUE THREAD

**Issue by thequailman** [candiddev/homechart#164]
## Requirements
- [x] Allow users to input color hex values (via a color picker) for color options in account preferences
- [x] Light text vs dark text picker?  https://stackoverflow.com/questions/12043187/how-to-check-if-hex-color-is-too-black
- [x] Make sure light/dark mode still inherits

## TODO
- [x] Alerts
- [x] Remove usage of `-invert` in a non-content context
- [x] Remove any specific --color_<red, orange, etc> references
- [x] Check color rendering of AuthHouseholdMembers
- [x] Canvas colors for graphs
- [x] OIDC button color
- [x] Print view
- [x] Add rot show-private-key
- [x] Add comments/generate new keys for passwords in rot.jsonnet
- [x] Remove Vault stuff
- [x] Update logo to be black on yellow instead of white
  - [x] Hugo
  - [x] Reddit
  - [x] Paddle
