### ISSUE TITLE
As a user, I want Homechart to expose an iCal feed so I can view the calendar in my native apps

### ISSUE THREAD

**Issue by thequailman** [candiddev/homechart#20]
## Requirements
- [ ] Calendar entries are exposed via iCal

## Todo
- [x] controllers/iCalRead
- [x] controllers/iCalUpdate change/delete ID
- [x] models/CalendarEventsReadiCal
- [x] models/PlanTasksReadiCal
- [x] types/Recurrence.iCal
- [x] types/iCal
- [ ] states/AuthAccount (ical ID and update ical)
- [ ] views/CalendarEvents iCal form
- [ ] views/SettingsAccount (ical URL and update ical)

**Comment by root9191** [comment]
this would be a really nice Feature 👍

**Comment by thequailman** [comment]
this was already implemented, you should see an option to setup an iCalendar URL under calendar.
