### ISSUE TITLE
Homechart v2023.05

### ISSUE THREAD

**Issue by thequailman** [candiddev/homechart#231]
## Bugs
- [x] Cook Meal Plan can't select a Meal Time correctly (ashley)
- [x] Health Items and Health Logs can't be created for children (items can't even select children, logs get created under parent) (discord)
- [x] Deleting accounts with transactions leaves lingering amounts in Budget Categories (email)
- [x] Microsoft Edge bugs with dates (email)
- [x] Selecting target month for Budget Category doesn't work (December doesn't change to November) (email)
- [x] Disabled rating field shouldnt show empty stars
- [x] long cook recipe names hide action buttons on mobile
- [x] cook Meal plan recipe field should create dynamic datalist after three characters are entered
- [x] can't update inventory quantity in the form (discord)
- [x] remove newsletter mortifications from database immediately otherwise they may resend while they are being sent
- [x] Daily agenda email (discord)
- [x] ICS showing wrong times for events (discord) swimming lessons
- [x] Add number of items to the collection names in the menu (discord)
- [x] Close calendar picker on input (Ashley)
- [x] License caching too long (email)

## TODO
- [x] Add WebPush config options to docs
- [x] Add WebPush setup to docs
- [x] Add QNAP docs: https://github.com/candiddev/homechart/discussions/234#discussioncomment-5809286
- [x] Remove Apple certificates, identifiers, devices, profiles, and keys
- [x] Remove Google/Apple things from Vault
- [x] Remove Mac vault
- [x] Remove Mac runner

## Post-Release
- [x] Newsletter
- [x] Blog post
- [x] Discord announcement
- [x] GitHub announcement
- [x] Reddit post

**Comment by root9191** [comment]
Hello,
i cannot login via App anymore on my selfhosted Instance..
![image](https://user-images.githubusercontent.com/47309435/235413984-6325ae61-7cc2-429e-a8b4-898a736afe75.png)
This is what the logs look like:

7:56:10
[ERROR] function='config.(*Vault).get:50 error='error updating config from vault: empty address or token'
7:56:10
[NOTICE] Starting server...

**Comment by thequailman** [comment]
is your iOS version up to date?  can you sign in using the web interface?

**Comment by root9191** [comment]
Yes its the newest version and there are no troubles logging in via web

**Comment by thequailman** [comment]
Can you try logging out of the iOS app/clearing all data from it?

**Comment by root9191** [comment]
I tried to log out, delete the app, rebooted the phone and installed it new but still the same..

**Comment by thequailman** [comment]
Just pushed out a new iOS version, can you install it and see if it works now?

**Comment by root9191** [comment]
thanks for your help but with the newest version the problem still isn't fixed. 
it looks like only the selfhosted Version is affected because i can login to web.homechart.app via app but on the selfhosted version i get the same error message after login..

**Comment by thequailman** [comment]
Found the bug, I have a fixed pushed and pending Apple's approval, will update this once it's done.

**Comment by thequailman** [comment]
Update should be available that fixes this, sorry!
